### ISSUE TITLE
你好，我想问一下专硕的封面如何添加企业导师？

### ISSUE THREAD

**Issue by lijincm** [a171232886/TJUThesis_master_2021#1]

**Comment by a171232886** [comment]
好问题。可参考“指导教师”进行修改。

- 首先需要在format.tex中定义关于“企业导师”的名称和内容，添加地点和方式可以参考“指导教师”（搜索\def\csupervisor 和\def\csupervisortitle就能看到，约第214行代码）。
- 然后添加显示（参考\csupervisor和\csupervisortitle，约format.tex第296行代码）。
- 最后在cover.tex中修改导师名称（参考\csupervisortitle和\csupervisor，约第48行代码）。

按照此方式可添加任意条目。
