### ISSUE TITLE
致谢段落没有首行缩进

### ISSUE THREAD

**Issue by Cqbelt** [a171232886/TJUThesis_master_2021#22]
致谢段落没有首行缩进，请问该怎么解决

**Comment by a171232886** [comment]
> 致谢段落没有首行缩进，请问该怎么解决

这应该open持续时间最短的问题

**Comment by qinghew** [comment]
咋解决的。。。

**Comment by qinghew** [comment]
是publications.tex里把专利下面的这段解除注释就行了。。。。（closed的确实快）
\vfill
\hangafter=1\hangindent=2em\noindent
\setlength{\parindent}{2em}
