### ISSUE TITLE
请教一下怎么在参考文献中引用网页

### ISSUE THREAD

**Issue by aidendrake0909** [a171232886/TJUThesis_master_2021#24]
请问各位大佬,怎么在参考文献中引用网页呢,例如http网页之类的
现在用@misc只显示网页名但是不显示网页

**Comment by a171232886** [comment]
要不要贡献一下解决方案

> 请问各位大佬,怎么在参考文献中引用网页呢,例如http网页之类的 现在用@misc只显示网页名但是不显示网页

**Comment by aidendrake0909** [comment]
直接将@misc里面的howpublished改成url就可以正常显示啦
